2017203053_김형석: disk.o fs.o testcase.o validate.o
	gcc -o 2017203053_김형석 disk.o fs.o testcase.o validate.o -no-pie

disk.o:disk.c
	gcc -c -o disk.o disk.c
fs.o:fs.c
	gcc -c -o fs.o fs.c
testcase.o:testcase.c
	gcc -c -o testcase.o testcase.c
clean:
	rm *.o 2017203053_김형석
